image: quay.io/aminrf/docker-kubectl:latest

services:
  - docker:dind

stages:
  - build
  - deploy


build:
  image: docker
  stage: build

  before_script:
    - docker login -u $REGISTERY_USERNAME_FRONT -p $REGISTERY_PASSWORD_FRONT quay.io

  script:
    - docker build ./CA9/my-app -t quay.io/mr_ali_the_great/ie_forntend_ca9:$CI_BUILD_REF
    - docker push quay.io/mr_ali_the_great/ie_forntend_ca9:$CI_BUILD_REF
    - docker rmi quay.io/mr_ali_the_great/ie_forntend_ca9:$CI_BUILD_REF || true

  after_script:
    - docker logout quay.io



deploy:
  stage: deploy
  when: manual
  script:
    - echo $KUBERNETES_CONFIG_FRONT | base64 -d > kube.config
    - kubectl --kubeconfig kube.config set image deployment/frontend-deployment frontend=quay.io/mr_ali_the_great/ie_forntend_ca9:$CI_BUILD_REF
    - rm kube.config
